### PR TITLE
Added support for custom headers

### PR DESCRIPTION
**Pull request by bhaskarmelkani**
1. Added support for adding custom headers in GET/POST/PUT/PATCH/DELETE requests.
2. Have  backward compatibility support.
3. Updated package.json, to add index.js and core.js in files.

### CODE REVIEW

**Comment by stomita** [comment]
Overloading body and settings might raise confliction. Consider the case apex method has parameters named 'headers' and 'body'.

**Comment by bhaskarmelkani** [comment]
I can do it like this.
`Apex.prototype.get = function(path, body, callback, headers) ` so that headers is an optional field.

Suggest any better way.

**Comment by stomita** [comment]
Aligning with other API interface in JSforce, adding optional `options` arg which can have `headers` property before `callback` arg would be preferable.

See http://jsforce.github.io/jsforce/doc/SObject.html#create

**Comment by bhaskarmelkani** [comment]
Hey, I have updated the signature. Check if its fine ? :)

**Pull request closed without merging**
