### PR TITLE
Allow the ability to programmatically specify a proxy when using the library in node.

### PR DESCRIPTION
**Pull request by aotimme**
This implements the ability to specify a proxy programmatically when using jsforce on the server as a node module. This pull request piggybacks on the `proxyUrl` parameter and passes it through to the `request` module's `proxy` parameter. This also provides a fix for jsforce/jsforce#1.

The issue for us with using the `HTTP_PROXY` environment variable is that then all outgoing requests (at least using the `request` library) would be forced to use the proxy. This is because the `request` library also respects the `HTTP_PROXY` environment variable (https://github.com/request/request#controlling-proxy-behaviour-using-environment-variables). In our use case, we want to force all jsforce requests to go through a proxy but we don't necessarily want all other requests in that same node process to use the proxy.

Usage (as in jsforce/jsforce#1):
```
var jsforce = require('jsforce');
var conn = new jsforce.Connection({
    proxy: 'http://proxy_url:port'
});
```

### CODE REVIEW

**Comment by aotimme** [comment]
Thanks for the feedback @stomita! Would you be more inclined to accept this if we create a new parameter `proxy` rather than overloading the `proxyUrl` parameter? If so I can make that change and you can review the updated pull request.

**Comment by stomita** [comment]
@aotimme I prefer "httpProxy" rather than "proxy".

**Comment by aotimme** [comment]
Thanks @stomita. Are you okay with the updated implementation otherwise? Specifically, are you okay with the new `ProxyServerTransport` class? I can call it `HttpProxyTransport` to be more in-line with using the term "httpProxy" if that sounds better.

**Comment by aotimme** [comment]
I just changed it to use the parameter "httpProxy" so the usage looks like:
```
var jsforce = require('jsforce');
var conn = new jsforce.Connection({
    httpProxy: 'http://proxy_url:port'
});
```
Let me know if there are any other changes you'd like to see.

**Comment by aotimme** [comment]
Thanks @stomita! Do you know when you're likely to issue a new release of this module (to npm) to include this? No worries if you don't have an estimate at this time.

**Comment by jayfresh** [comment]
:+1: for releasing an update to npm

**Pull request merged**
