### PR TITLE
fix: combine all batches from bulk api into single stream

### LINKED ISSUE #429: Handle multiple bulk query result seamleslly in a stream
Fix [this](https://github.com/jsforce/jsforce/blob/1.6.0/lib/api/bulk.js#L801-L803)

Related issue: #428

### PR DESCRIPTION
**Pull request by stomita**
Close #429 #428

### CODE REVIEW

**Comment by tejasmanohar** [comment]
Hmm does jsforce keep data from the stream in-memory somewhere? I seem to be getting OOMs after switching from my own handling to JSForce.

**Comment by stomita** [comment]
It is assumed that the bulk query returns a record stream (= the stream contains record object) which parses the returned CSV only when any record stream consumer is connected. As current CSV  parser stores CSV string in memory the parsing may fail if the returned text is too large. 
If you are using record stream and get fail you can bypass the CSV parser by directly consuming retuned raw stream.

**Comment by tejasmanohar** [comment]
When directly consuming the raw stream without the CSV parser (`.stream()`), it seems I'm facing OOMs still. May have some time to do a heapdump next week to see what's causing that, but it does not happen with my implementation of the bulk request stream -> csv parsing w/o jsforce.

**Comment by tejasmanohar** [comment]
@stomita Would you please release this to NPM? Thanks!

**Pull request merged**
